apiVersion: v1
kind: List
metadata:
  name: redhat-ipaas-ci
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ipaas-ci
      template: redhat-ipaas-ci
    name: jenkins
  spec:
    replicas: 1
    selector:
      name: jenkins
    strategy:
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: ipaas-ci
          name: jenkins
      spec:
        containers:
        - env:
          - name: OPENSHIFT_ENABLE_OAUTH
            value: "true"
          - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
            value: "true"
          - name: KUBERNETES_MASTER
            value: https://kubernetes.default:443
          - name: KUBERNETES_TRUST_CERTIFICATES
            value: "true"
          - name: JNLP_SERVICE_NAME
            value: jenkins-jnlp
          image: openshift/jenkins-2-centos7@sha256:748cf60cc2067f4b933deffe132dd84383330fa972f2a8b376bcb225fb80f41c
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 420
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          name: jenkins
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              memory: 2Gi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/jenkins
            name: jenkins-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        serviceAccount: ipaas-ci
        serviceAccountName: ipaas-ci
        terminationGracePeriodSeconds: 30
        volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-data
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - jenkins
        from:
          kind: ImageStreamTag
          name: jenkins:2
          namespace: openshift
        lastTriggeredImage: openshift/jenkins-2-centos7@sha256:748cf60cc2067f4b933deffe132dd84383330fa972f2a8b376bcb225fb80f41c
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 1
    details:
      causes:
      - imageTrigger:
          from:
            kind: ImageStreamTag
            name: jenkins:2
            namespace: openshift
        type: ImageChange
      message: caused by an image change
    latestVersion: 2
    observedGeneration: 3
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: ipaas-ci
    name: jenkins-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    volumeName: jenkins-data
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: ipaas-ci
    name: m2-repo
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    volumeName: m2-repo
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: jenkins
    name: jenkins
    namespace: ipaas-ci
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: jenkins:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/redhat-ipaas/jenkins.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jenkins-2-centos
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - type: ConfigChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: jenkins
    name: jenkins
    namespace: ipaas-ci
  spec: {}
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: jenkins
    labels:
      app: ipaas-ci
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: ipaas:admins
    labels:
      app: ipaas-ci
  roleRef:
    name: admin
  subjects:
  - kind: ServiceAccount
    name: jenkins