apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jenkins-2-persistent
  name: jenkins-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: jenkins-data
